acquisition_dir: "D:\\data"
behavior_dir: "D:\\behavior\\data"
platform: multiplane_ophys
manifest_directory: "D:\\aind-watchdog-service-manifest"
s3_bucket: "s3://aind-watchdog-service"
capsule_id: "capsule_id"
destination: "D:/ophys"
schemas:
  - rig.json
  - session.json
modalities: # What files and modalities service is expected to move; glob patterns OK
  ophys: 
    - "*_averaged_depth.tiff"
    - "*_averaged_surface.tiff"
    - "*cortical_z_stack*.tiff"
    - "*fullfield.roi"
    - "*fullfield.tiff"
    - "*local_z_stack*.tiff"
    - "*platform.json"
    - "*reticle.tif"
    - "*stim.pkl"
    - "*surface.roi"
    - "*sync.h5"
    - "*timeseries.roi"
    - "*timeseries.tiff"
    - "*vasculature.tif"
    - session.json
    - rig.json
  behavior:
    - "*Behavior*.mp4"
    - "*Face*.mp4"
    - "*Eye*.mp4"
    - "*Behavior*.json"
    - "*Face*.json"
    - "*Eye*.json"